/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottonConfirm: typeof import('./src/components/BottonConfirm.vue')['default']
    BottonConfirmPc: typeof import('./src/components/pc/BottonConfirmPc.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight.vue')['default']
    CopyRightPc: typeof import('./src/components/pc/CopyRightPc.vue')['default']
    PopoverView: typeof import('./src/components/pc/PopoverView.vue')['default']
    ScrollView: typeof import('./src/components/ScrollView.vue')['default']
    TabsView: typeof import('./src/components/pc/TabsView.vue')['default']
    VanCol: typeof import('vant/es')['Col']
    VanDivider: typeof import('vant/es')['Divider']
    VanImage: typeof import('vant/es')['Image']
    VanPopover: typeof import('vant/es')['Popover']
    VanRow: typeof import('vant/es')['Row']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoBackGround: typeof import('./src/components/VideoBackGround.vue')['default']
  }
}
