/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VanImage: typeof import('vant/es')['Image']
    VanPopover: typeof import('vant/es')['Popover']
    VanRow: typeof import('vant/es')['Row']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VideoBackGround: typeof import('./src/components/VideoBackGround.vue')['default']
  }
}
